; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+8 on Tue Mar 26 2024 13:50:10 GMT+0000 (Greenwich Mean Time)
M561 ; clear any bed transform
;G29  ; probe the bed and enable compensation


