; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+8 on Tue Mar 26 2024 13:50:11 GMT+0000 (Greenwich Mean Time)
M98 P"homex.g"
M98 P"homey.g"
M98 P"homez.g"

; Uncomment the following lines to lift Z after probing
;G91                  ; relative positioning
;G1 Z5 F100           ; lift Z relative to current position
;G90                  ; absolute positioning


