; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+8 on Tue Mar 26 2024 13:50:12 GMT+0000 (Greenwich Mean Time)
M83            ; relative extruder moves
G1 E-5 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X110 Y110 F6000 ; go to X=110 Y=110

