; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+8 on Tue Mar 26 2024 13:50:13 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

